name: BetterSpectator
version: 2.1
author: engels
main: com.engels.betterspectator.BetterSpectator
api-version: 1.8.9
commands:
  vanish:
    description: makes you invisible to other players
    usage: /<command>
  unvanish:
    description: makes you visible to other players
    usage: /<command>
  clip:
    description: makes you spectate player
    usage: /<command> [player]
  spec:
    description: makes you spectate player in freecam mode
    usage: /<command> [player]
  exit:
    description: ends your spectation of player
    usage: /<command>
  inv:
    description: gives you player's inventory
    usage: /<command> [player]
  next:
    description: makes you spectate next player (must already spectate one!)
    usage: /<command>
  prev:
    description: makes you spectate prev player (must already spectate one!)
    usage: /<command>
  showall:
      description: used for test purpouses
      usage: /<command>
  wipe:
      description: wipes player`s kill count
      usage: /<command> [player]
depend:
  - ActionBarAPI

